# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    - CONFIG=osx_python3.6

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "Jwxjo04We5EnVvN5HS3cNgod1k5z4lRrxXAHkAl5uvnnx7IEBPdkCk0bYPi8N9ghjlF+lnnuh8v+WvEtwPDBFyy7/FJrvBKGu9VqjXSKLsEZk5pXJuBnaYymYH0ldNz7W4ypwN2j1+xn0u6Xc8Tix3bpl9mWIktxnijQ59rOKrOqoY4aNS8ZD/CiHaE2ASo/kuA7hJ1gXy63mIfUakDXO74wYrXIotQ8og/2qjF2aaSVlUlD4ZZ+He9YRYfqDt3RZZm1WBZlRB/Jzpv6xjzIdJZh4GplQAgrGlPxEEuCZdlefmRHtwG/4iKRl00fpAp7Ocz9VbtskuwcI/mf58M3aeXpn801EkIMEGbrGcJfbuKpAjz3wfXi+8wgiMmsUDyqFjInXRu4bOYDMlBWu/zQBWUBWQWpzIIWrfay19H0P8DnOdySHODwkh6jqW8oNUOamRMwqu0EfbWAwId2LYMKaWtzVPEluKhM+XZiDboCYFOHu8rcfEYXrZgTUPc7JkY9WofRhg4R23KLHxyfZtCy6GbkJ5uPayMtMMdZ+ebuzhBE4mTRmDWuK7CoSuF7YYHB4aSiSosEQe74/bPRcOGjlS6peB95A/yo3qxNr+96O5GpRa8if6JMxMqJd2V5rvqSSfUiRYNChHtUK+2nEMPKBFPeCFsfiq8t0aLXGBYLN5M="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-ci-setup=1
      source run_conda_forge_build_setup

script:
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml

  - upload_or_check_non_existence ./recipe conda-forge --channel=main -m ./.ci_support/${CONFIG}.yaml
