travis:
  secure:
    BINSTAR_TOKEN: Jmo4ldI43sf3jbijGjwkvoJNCwNyF2DrjCcraEGR10IgWWSFDz7lmhJKwDfwWgLJOwouGlYjBW7f+nK2P/qSJDz9BkATPPfSYH+KSPuMXHHBVIoZzBSVhJSVMpCyE8518krG05fl/qaWQjrsmepWVGcCVqLk5BnlyqW4rLZercq7UGnekx8I88C5JQAmQk3tUf+Iz1j+ZF/NMA9FUTwWB9HGNhMsFI5rOsmXajKzyG+x3F1cftLvgy/0RLQnsbwpDni9Co9YNUVD+whm1jj14EeUh9iRhMlxLdCroaTpJaxb/YfVmv1hVITtoOeos/WaBL4LYT6Gg3OVAF/F4Qh5q/wq5vfjCiIVfimTHmLOwuFB97TlC2SWfL5OGRCHnsoQp7ne8MftE+6edKatPP1RyIRQ3AvGWdIUSvb/6YN1ajrB+4DDuBa2OyuhBYiYKpuoLBR/CEtYU1a+wBvUHqYt5lzbPKchOlo7NHltjtBMCPtwBD6vsDnvoHbOXOjAncIcFzDgnWXoN1g/9tww58CsTsrLLxIjfhkHvpgRev42UM0EqnrvMD9ICG1NE6Czs7QMhtqL6ING0hQ/IdJGsi47x1DFiF/vEmiG74GsC2xLmhclHk/Sj3/gsLJUMrCWopyZkg6k2Vjavf8KbjndXn+H/bezshtFV6C/Y0a6+fYjQX8=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
