travis:
  secure:
    BINSTAR_TOKEN: Jwxjo04We5EnVvN5HS3cNgod1k5z4lRrxXAHkAl5uvnnx7IEBPdkCk0bYPi8N9ghjlF+lnnuh8v+WvEtwPDBFyy7/FJrvBKGu9VqjXSKLsEZk5pXJuBnaYymYH0ldNz7W4ypwN2j1+xn0u6Xc8Tix3bpl9mWIktxnijQ59rOKrOqoY4aNS8ZD/CiHaE2ASo/kuA7hJ1gXy63mIfUakDXO74wYrXIotQ8og/2qjF2aaSVlUlD4ZZ+He9YRYfqDt3RZZm1WBZlRB/Jzpv6xjzIdJZh4GplQAgrGlPxEEuCZdlefmRHtwG/4iKRl00fpAp7Ocz9VbtskuwcI/mf58M3aeXpn801EkIMEGbrGcJfbuKpAjz3wfXi+8wgiMmsUDyqFjInXRu4bOYDMlBWu/zQBWUBWQWpzIIWrfay19H0P8DnOdySHODwkh6jqW8oNUOamRMwqu0EfbWAwId2LYMKaWtzVPEluKhM+XZiDboCYFOHu8rcfEYXrZgTUPc7JkY9WofRhg4R23KLHxyfZtCy6GbkJ5uPayMtMMdZ+ebuzhBE4mTRmDWuK7CoSuF7YYHB4aSiSosEQe74/bPRcOGjlS6peB95A/yo3qxNr+96O5GpRa8if6JMxMqJd2V5rvqSSfUiRYNChHtUK+2nEMPKBFPeCFsfiq8t0aLXGBYLN5M=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
